### ISSUE TITLE
Valid OAuth redirect URI

### ISSUE THREAD

**Issue by VipulSolanki90** [ccoenraets/OpenFB#1]
What should i write in Valid OAuth redirect URIs in facebook application advanced settings?

**Comment by dhavalrajani92** [comment]
hello,

i have set this 'https://www.facebook.com/connect/login_success.html' url as valid oAuth url in facebook app but getting following error at facebook page of android phone 

given url is not allowed by the application configuration : one or more of the given URLs is not allowed by the app’s settings. To use ths URL you must add a valid native platform in your app’s settings

 can any one help me to configure my facebook app for facebook login in meteor android/ios app??

i have also posted question on stackoverflow 
http://stackoverflow.com/questions/32539886/facebook-login-using-meteor-cordova-app

**Comment by xgenem** [comment]
Did you make sure you added the plugin?

**Comment by dhavalrajani92** [comment]
yes i have added plugin com.phonegap.plugins.facebookconnect@0.11.0

**Comment by xgenem** [comment]
Did you have the AP ID included in your init() call?

**Comment by dhavalrajani92** [comment]
i am developing meteor app so this plugin is handling all thing i have specified app id in mobile-config.js

**Comment by xgenem** [comment]
It should be when you initialize the plugin

**Comment by dhavalrajani92** [comment]
yes i declared
