### ISSUE TITLE
How to remove session from app

### ISSUE THREAD

**Issue by Sabirahmed** [ccoenraets/OpenFB#10]
Hi, 
I have used your code and it's working fine. but when i logout from my app and again login it's not asking for userid and password. It's show successfull login message and redirect to next screen.
Could you, let me know how to remove access_token from session?

Thanks,

**Comment by PiJoules** [comment]
+1 This works for me. Thanks.

**Comment by ccoenraets** [comment]
PR merged. Now using clearcache.
