### ISSUE TITLE
No oAuth Settings in Facebook?

### ISSUE THREAD

**Issue by asantaga** [ccoenraets/OpenFB#108]
Hey all,
Am I missing something or are the docs no longer valid?? 

In the docs it says 

"In the OAuth Settings section, add the following URLs in the Valid OAuth redirect URIs field:

http://localhost:8100/oauthcallback.html (for access using ionic serve)
https://www.facebook.com/connect/login_success.html (for access from Cordova)"

However in the facebook https://developers.facebook.com/apps screens there is no oAuth field..

Has this moved?

**Comment by tujlaky** [comment]
I found it:
![screencapture-developers-facebook-com-sa-apps-407262672806525-fb-login-1462741440096](https://cloud.githubusercontent.com/assets/412917/15100437/c744c5d8-1571-11e6-8e8a-6db9b89c30e9.png)

Product settings sections: Add product, then Facebook login

**Comment by asantaga** [comment]
thanks yes!, there it is..

**Comment by asantaga** [comment]
thanks yes!, there it is..
