### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by panickz** [ccoenraets/OpenFB#20]
Hi, Iºm having an issue I´m not quite sure how to solve it. First. I´m creating a PhoneGap APP so wich should be my oauth url since the user will have an APP and not a website APP. 

After I click login I get a blank screen. No errors just a blank screen ( inApp and Web ). I don't know how to solve this.

Cheers,
DAniel SOusa

**Comment by betoharres** [comment]
the blank screen is just because you haven't defined the var errorHandler. I did a copy & paste from his blogspot and was getting the same issue.

**Comment by panickz** [comment]
This is closed. Sorry for the delay.
