### ISSUE TITLE
oauthRedirectURL is not correct with folders two levels deep

### ISSUE THREAD

**Issue by kmturley** [ccoenraets/OpenFB#38]
When running the script locally with two folder levels e.g.
http://localhost:8888/example-app/www/

The callback url comes out as:
http://localhost:8888/example-app/oauthcallback.html
http://localhost:8888/example-app/logoutcallback.html 

This should actually be:
http://localhost:8888/example-app/www/oauthcallback.html
http://localhost:8888/example-app/www/logoutcallback.html

I fixed by changing line 20 from:
context = window.location.pathname.substring(0, window.location.pathname.indexOf("/",2))

to:
context = window.location.pathname.substring(0, window.location.pathname.lastIndexOf("/"))

**Comment by mikkokam** [comment]
@kmturley Thanks! Your **lastIndexOf** works.

    context = window.location.pathname.substring(0, window.location.pathname.lastIndexOf("/")),

**Comment by ccoenraets** [comment]
Thanks. Fixed in 0.5.
