### ISSUE TITLE
How to implement Facebook v2.2

### ISSUE THREAD

**Issue by jadman02** [ccoenraets/OpenFB#53]
I added v2.2 to the login URL (because otherwise login won't work after April 2015 https://developers.facebook.com/docs/apps/changelog#v2_2) and now none of the facebook calls work...but it does work without the v2.2

var FB_LOGIN_URL = 'https://www.facebook.com/v2.2/dialog/oauth',

**Comment by braco** [comment]
https://developers.facebook.com/docs/apps/upgrading#v1tov2

**Comment by ccoenraets** [comment]
```
openFB.init({appId: 'YOUR_FB_APP_ID',
                    loginURL: 'https://www.facebook.com/v2.3/dialog/oauth'});
```

```
openFB.api({
            path: '/v2.3/me',
            success: function(data) {
            },
            error: function(error) {
            });
```
