### ISSUE TITLE
How to correctly return the user to a new state in the Emulator?

### ISSUE THREAD

**Issue by kramer65** [ccoenraets/OpenFB#54]
I'm trying to use OpenFB in my Ionic app, and in the browser it now works fine with the following login controller:
```
 .controller('LoginCtrl', function($scope, $state){
        $scope.fbLogin = function(){
            openFB.login(
                function(response){
                    if (response.status == 'connected'){
                        console.log('Facebook login succeeded. YEAH!!!');
                        $state.go('tab.chats');
                    } else {
                        console.log('The FB login failed.');
                    }
                },
                {scope: 'email, publish_actions'}
            );
        }
    })
```

The problem is that when I try this in the emulator, I get redirected to the FB view and I can login, but after that view I get a screen giving me a safety warning which says (translated from Dutch) something like this:

> SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Center for more information.

I don't get this warning in the browser though. Does anybody know why this is and how I can solve it? All tips are welcome!

**Comment by AgentChris** [comment]
i have the same problem

**Comment by ccoenraets** [comment]
Looks like Cordova is nor properly configured:

1. Make sure you include cordova.js in index.html
    ```
   <script src="cordova.js"></script>
    ```
    
    cordova.js doesn't have to (and should not) be present in your www folder. It is injected by the cordova build process. 

2. Make sure you installed the inappbrowser plugin
    ```
   cordova plugins add org.apache.cordova.inappbrowser
    ```

3. Make sure that your redirect URL matches what you declared when creating your FB app
