### ISSUE TITLE
openFB & Android (not working)

### ISSUE THREAD

**Issue by thiagosoeiro** [ccoenraets/OpenFB#66]
Hi, I have an app that keeps showing this error and I can't find a solution for this:
![error](https://cloud.githubusercontent.com/assets/9267122/7523466/54f110d8-f4d2-11e4-9023-7734d25988c1.jpg)

I'm using default oauth redirec tURL:
oauthRedirectURL = "https://www.facebook.com/connect/login_success.html"; 
By the way, the app is working fine on iOS.

**Comment by jtangelder** [comment]
I've got this issue too. I'm wondering how you've fixed this, since this issue is closed the next day.

**Comment by roulder** [comment]
Any solutions?
